services:
  ingestor:
    build: .
    container_name: ingestor
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend

  redis:
    image: redis:8.6.2-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis_data: